### ISSUE TITLE
README needs to be updated?

### ISSUE THREAD

**Issue by adrianboyko** [anacrolix/stm#1]
Hi. The README seems to imply that the "Operation" passed to Atomically should not return a value, but the type definition in the code says that it must return interface{}. Is the README out of sync with the code?

**Comment by anacrolix** [comment]
Yeah, the documentation is out of sync with the code. There's now `VoidOperation` to wrap functions that return no value. The original author mentioned that he wasn't sure whether returning values was necessary, and I believe that it was. This `stm` implementation is heavily used in `anacrolix/dht` if you're curious about how that looks (returning `IO` actions and flags essentially).

**Comment by anacrolix** [comment]
Should be fixed in v0.3.0, along with a note for the other examples.
