### ISSUE TITLE
Support generics

### ISSUE THREAD

**Issue by chrismwendt** [anacrolix/stm#2]
Now that [Go 1.18 has generics](https://go.dev/doc/tutorial/generics), generics could be added and the disclaimer in the README could be dropped!

**Comment by anacrolix** [comment]
This was pursued in a branch. I didn't finish due to incompleteness with generics at the time. This could be followed up and completed.

**Comment by chrismwendt** [comment]
Found the branch https://github.com/anacrolix/stm/tree/go2 Coincidentally you and I took the same approach: make an interface `txVar` for keys of the maps in `Tx` 😸

**Comment by anacrolix** [comment]
I used to use this heavily in anacrolix/dht. I switched to a more conventional approach for performance and simplicity reasons (although with generics this would be nice to revisit). I would love to know where anyone is using STM in Go, and of any downstream users of this module.

**Comment by anacrolix** [comment]
I've released the version with generics as `v0.4.0`.
